export const SELECTORS = {
  container: '.container',
  circle: '.circle',
  containerForForm: '.content',
  statInfContainer: '#stat',
  button: '.btn',
  input: '.input',
  inputAddTask: '#input',
  header: '.header',
  deleteAllBtn: '#b1',
  deleteLastBtn: '#b2',
  error: '.error',
  addBtn: '#b3',
  underHeaderBlock: '#und',
  showAllTasksBtn: '#b4',
  showMadeTasksBtn: '#b5',
  searchInput: '#searchInput',
  toDoBlock: '#content',
  saveBtn: '#save',
  closeBtn: '#close',
  form: '.add-task-form',
  taskBlock: '.task-block',
  circleTwo: '#circleTwo'
}
